name: iOS

on: [push, pull_request]

jobs:
  build-ios-clang:
    strategy:
      matrix:
        config: [Debug, Release]

    runs-on: macos-latest
    name: MacOS -> iOS, ${{ matrix.config }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Download Vulkan SDK
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/BuildTools/Scripts/github_actions
        chmod +x vulkan_sdk.sh
        ./vulkan_sdk.sh

    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{runner.workspace}}/build_cache
        key: ios-${{ matrix.config }}-${{ hashFiles('ThirdParty/glslang/*', 'ThirdParty/SPIRV-Cross/*', 'ThirdParty/SPIRV-Tools/*', 'ThirdParty/SPIRV-Headers/*') }}

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/BuildTools/Scripts/github_actions
        chmod +x configure_cmake.sh
        ./configure_cmake.sh "ios" "${{runner.workspace}}" ${{ matrix.config }} "" ${{ steps.cache.outputs.cache-hit != 'true' }}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} --target install -j2

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: ${{ success() && matrix.config == 'Release' }}
      with:
        name: DiligentCore-iOS-arm64-${{ matrix.config }}
        path: |
          ${{runner.workspace}}/build/install/
          !${{runner.workspace}}/build/install/**/*.a
        retention-days: 90
